name: Deploy website

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest codebase
        uses: actions/checkout@v3

      - name: Deploy website
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'https://acehack.uem.edu.in'
          project: '.'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
